# -*- coding: utf-8 -*-
"""KashDash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138QsFuZ5df1VMGo_1wXIRjPjWASJhW5L
"""


import streamlit as st
import pandas as pd
from datetime import datetime

st.set_page_config(page_title="Money Moves with Meaning", layout="centered")
st.title("\U0001F4B8 Money Moves with Meaning")
st.markdown("#### A KashFlow Insights Tool to Track Your Financial Peace")

# Input sections
st.sidebar.header("Add a Transaction")
date = st.sidebar.date_input("Date", value=datetime.today())
category = st.sidebar.selectbox("Category", ["Income", "Bills", "Groceries", "Self-Care", "Spiritual", "Business", "Other"])
description = st.sidebar.text_input("Description")
amount = st.sidebar.number_input("Amount ($)", step=0.01)
add = st.sidebar.button("Add Transaction")

# Session state for tracking transactions
if 'transactions' not in st.session_state:
    st.session_state.transactions = pd.DataFrame(columns=["Date", "Category", "Description", "Amount"])

if add:
    new_transaction = pd.DataFrame({
        "Date": [date],
        "Category": [category],
        "Description": [description],
        "Amount": [amount]
    })
    st.session_state.transactions = pd.concat([st.session_state.transactions, new_transaction], ignore_index=True)

# Display dashboard
st.subheader("Your KashFlow Summary")
df = st.session_state.transactions
if not df.empty:
    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values(by="Date", ascending=False)

    st.dataframe(df)

    total_income = df[df["Category"] == "Income"]["Amount"].sum()
    total_expenses = df[df["Category"] != "Income"]["Amount"].sum()
    balance = total_income - total_expenses

    st.metric("Total Income", f"${total_income:,.2f}")
    st.metric("Total Expenses", f"${total_expenses:,.2f}")
    st.metric("Remaining Balance", f"${balance:,.2f}", delta_color="normal")

    st.bar_chart(df.groupby("Category")["Amount"].sum())
else:
    st.info("Add a transaction to begin tracking your finances.")
